var searchData=
[
  ['packages_0',['-If you can and you want to take it directly from the system you can do this instead: pip install pyopengl matplotlib pyqt5 pandas &amp;ndash;break-system-packages.',['../md_README.html#autotoc_md2',1,'']]],
  ['pandas_1',['pandas',['../md_README.html#autotoc_md3',1,'-Show if you have all of this instalations you can do: python3 -m pip show pyopengl matplotlib pyqt5 pandas.'],['../md_README.html#autotoc_md1',1,'-We have this dependecies to run the proyect: pip install pyopengl matplotlib pyqt5 pandas.']]],
  ['pandas_20ndash_20break_20system_20packages_2',['-If you can and you want to take it directly from the system you can do this instead: pip install pyopengl matplotlib pyqt5 pandas &amp;ndash;break-system-packages.',['../md_README.html#autotoc_md2',1,'']]],
  ['particles_20charge_20from_20a_20csv_20and_20the_20energy_20normalized_20that_20the_20particles_20have_20and_20where_20are_20they_20in_20the_20space_3',['My code only shows you in 3D particles charge from a CSV and the energy (normalized) that the particles have and where are they in the space.',['../md_README.html#autotoc_md5',1,'']]],
  ['pip_20install_20pyopengl_20matplotlib_20pyqt5_20pandas_4',['-We have this dependecies to run the proyect: pip install pyopengl matplotlib pyqt5 pandas.',['../md_README.html#autotoc_md1',1,'']]],
  ['pip_20install_20pyopengl_20matplotlib_20pyqt5_20pandas_20ndash_20break_20system_20packages_5',['-If you can and you want to take it directly from the system you can do this instead: pip install pyopengl matplotlib pyqt5 pandas &amp;ndash;break-system-packages.',['../md_README.html#autotoc_md2',1,'']]],
  ['pip_20show_20pyopengl_20matplotlib_20pyqt5_20pandas_6',['-Show if you have all of this instalations you can do: python3 -m pip show pyopengl matplotlib pyqt5 pandas.',['../md_README.html#autotoc_md3',1,'']]],
  ['proyect_3a_20pip_20install_20pyopengl_20matplotlib_20pyqt5_20pandas_7',['-We have this dependecies to run the proyect: pip install pyopengl matplotlib pyqt5 pandas.',['../md_README.html#autotoc_md1',1,'']]],
  ['pyopengl_20matplotlib_20pyqt5_20pandas_8',['pyopengl matplotlib pyqt5 pandas',['../md_README.html#autotoc_md3',1,'-Show if you have all of this instalations you can do: python3 -m pip show pyopengl matplotlib pyqt5 pandas.'],['../md_README.html#autotoc_md1',1,'-We have this dependecies to run the proyect: pip install pyopengl matplotlib pyqt5 pandas.']]],
  ['pyopengl_20matplotlib_20pyqt5_20pandas_20ndash_20break_20system_20packages_9',['-If you can and you want to take it directly from the system you can do this instead: pip install pyopengl matplotlib pyqt5 pandas &amp;ndash;break-system-packages.',['../md_README.html#autotoc_md2',1,'']]],
  ['pyqt5_20pandas_10',['pyqt5 pandas',['../md_README.html#autotoc_md3',1,'-Show if you have all of this instalations you can do: python3 -m pip show pyopengl matplotlib pyqt5 pandas.'],['../md_README.html#autotoc_md1',1,'-We have this dependecies to run the proyect: pip install pyopengl matplotlib pyqt5 pandas.']]],
  ['pyqt5_20pandas_20ndash_20break_20system_20packages_11',['-If you can and you want to take it directly from the system you can do this instead: pip install pyopengl matplotlib pyqt5 pandas &amp;ndash;break-system-packages.',['../md_README.html#autotoc_md2',1,'']]],
  ['python3_20m_20pip_20show_20pyopengl_20matplotlib_20pyqt5_20pandas_12',['-Show if you have all of this instalations you can do: python3 -m pip show pyopengl matplotlib pyqt5 pandas.',['../md_README.html#autotoc_md3',1,'']]]
];
